### ISSUE TITLE
Pallet.cs 신텍스 에러

### ISSUE THREAD

**Issue by dhsong215** [dhsong215/pacman#24]
#19 에서 병합된 Pallet.cs에서 신텍스 에러가 나옵니다.
<img width="531" alt="스크린샷 2024-05-14 오후 10 02 42" src="https://github.com/dhsong215/pacman/assets/77286910/7db723d3-01e9-42da-8e23-5d4818ebfe74">

에러 구문
```c#
private void OnTriggerEnter2D(Collider 2D other)
{
    if (other.gameObject.layer == LayerMask.NameToLayer("Pacman")) {
        Eat();
    }
}
```

**Comment by ohrion0320** [comment]
확인했습니다!
